### ISSUE TITLE
Awesome! First lib with Audio Controls

### ISSUE THREAD

**Issue by Noitidart** [App2Sales/react-native-hue-player#3]
Thanks for this lib very much! Pretty much all of the react-native sound moduls are just imperative APIs for playing sound files, there is nothing out there with "controls".

This package seems to use the "native" controls from the screenshot. Is this true for Android and iOS?

Also is this package ready to use? I found this as it was listed in the "dependents" of react-native-sound - https://www.npmjs.com/browse/depended/react-native-sound

Thanks very much!

**Comment by marumaia** [comment]
Hey there, @Noitidart !
Thank you for your kind words!

This package is ready to use on Android, but we didn't finish the tests on iOS and the documentation of the AudioController is not complete (sorry about that).

About the dependency, you will only need to link those packages in order to make it work. In case you have any problem doing it you can look at the documentation on their repositories (we listed on the readme file).

We'll post the iOS screenshots and the additional documentation pretty soon.

Hope you enjoy our HUE Player!
Best Regards!
