### ISSUE TITLE
Local file not loaded and other things.

### ISSUE THREAD

**Issue by Angelk90** [App2Sales/react-native-hue-player#5]
@App2Sales, @ssscassio, @wendelrego : 

Hi, congratulations on the project.
I tried it, but strange things happened to me.

- The local file is not loaded, I have specified the path in this way:

```
    author: 'Jack',
    url: '',
    path: './mp3/Lost Frequencies feat. Janieck Devy - Reality (Official Music Video).mp3',
```

- The transition from one song to another is very slow.

- When I close the app, the music player still remains in the noticias area.

Code:
```
const playlist = [
  {
    key: 'audio01',
    title: 'Hino do Brasil',
    author: 'Francisco Manuel da Silva',
    url: 'http://www.noiseaddicts.com/samples_1w72b820/4170.mp3',
    thumbnail: 'http://www.aprocura.com.br/wp-content/uploads/2012/10/Significado-Cores-Bandeira-do-Brasil.jpg'
  },
  {
    key: 'audio02',
    title: 'Hello',
    author: 'Adele',
    url: 'http://sv10.onlinevideoconverter.com/download?file=f5j9d3j9a0c2j9',
    thumbnail: 'http://www.thissongslaps.com/wp-content/uploads/2015/11/Nicholas-Minaj.jpg'
  },
  {
    key: 'audio03',
    title: 'Adele - Someone Like You',
    author: 'Adele2',
    url: 'http://s18.onlinevideoconverter.com/download?file=h7d3i8a0j9j9a0b1',
    thumbnail: 'https://vignette3.wikia.nocookie.net/adeles/images/a/aa/Someone_like_you_photoshoot.png/revision/latest?cb=20150614040024'
  },
  {
    key: 'audio04',
    title: 'Lost Frequenz',
    author: 'Jack',
    url: '',
    path: './mp3/Lost Frequencies feat. Janieck Devy - Reality (Official Music Video).mp3',
    thumbnail: 'https://i.ytimg.com/vi/kkyR1CoWlv8/maxresdefault.jpg'
  },
  {
    key: 'audio05',
    title: 'Adele - Rolling in the Deep',
    author: 'Adele3',
    url: 'http://sv22.onlinevideoconverter.com/download?file=c2g6g6j9h7h7',
    thumbnail: 'https://orig00.deviantart.net/878c/f/2011/200/5/6/adele___rolling_in_the_deep_by_migslins-d40wp2y.jpg'
  }
];
```

**Comment by jkdrangel** [comment]
@marumaia

**Comment by marumaia** [comment]
Hi there @Angelk90 !
Thanks for your feedback! 

On your first issue, about loading local file, the path is the problem. To handle local files you need to follow some rules defined on the [React Native Sound documentation](https://github.com/zmxv/react-native-sound):

> Save your sound clip files under the directory android/app/src/main/res/raw. Note that files in this directory must be lowercase and underscored (e.g. my_file_name.mp3) and that subdirectories are not supported by Android.

We do need to update our documentation and include this restrictions.

About the slow transition between tracks, we'll take a look on how can we improve it. In meantime be sure your internet is OK, since all your tracks are streamings.

On the last item, was the player still open on notification bar, even though you completely closed the app? Can you give more details on this issue? We couldn't reproduce over here. When the app goes to background the player should be there, but once the app is finished the Music Control element should be closed.
